### ISSUE TITLE
Get IDs of points in a cluster

### ISSUE THREAD

**Issue by alexcarruthers** [wemap/pysupercluster#5] opened 2019-03-27 15:35 UTC
I was wondering if I could make a feature request?

We want to be able to see which points are in a cluster (in order to list them on a map/provide some sort of view). Is it possible to attach an ID to each input coordinate pair and have pysupercluster (optionally) list the list of IDs attached to each cluster?

**Comment by jlaine** [comment] 2019-03-27 16:13
Hi! This looks like a duplicate of #1, let's move the discussion there

**Closed by jlaine** 2019-03-27 16:13 UTC

**Comment by Duoquote** [comment] 2023-06-06 06:34
Any updates here?
